# Generated by Django 4.2.7 on 2025-06-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this mandate is currently active. Can be set to False when mandate is completed or cancelled.'),
        ),
    ]
