# Generated by Django 4.2.7 on 2025-07-14 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_invoice_timeentry_is_billable_timeentry_is_invoiced_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(help_text='Name of the field that changed', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (JSON serialized)', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value (JSON serialized)', null=True)),
                ('change_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], help_text='Type of change operation', max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When the change occurred')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('changed_by', models.ForeignKey(help_text='User who made the change', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['content_type', 'object_id'], name='core_change_content_4a6b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['changed_by'], name='core_change_changed_2fa87d_idx'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['changed_at'], name='core_change_changed_3a0b99_idx'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['change_type'], name='core_change_change__f34b21_idx'),
        ),
    ]